repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
        exclude: ^\.bumpversion\.cfg$
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: https://github.com/APIDevTools/swagger-cli
    rev: v4.0.4
    hooks:
      - id: swagger-validation
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.52.2
    hooks:
      - id: golangci-lint
