#
# Copyright (c) 2018 Junpei Kawamoto
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
language: go
go:
  - "1.10"
before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
install:
  - dep ensure
script:
  - go test -v ./...
notifications:
  slack:
    rooms:
      secure: Re3k88FXBasj/39o6twM8AMduJPP2pdX/hT+T+zcZzkp/Sdfr6djSHcINYVOJEDvpP4uGBaWKjIecbxV1wPpb19Xh/J2DXio6LVEggXUO4tHb2Ub+Y5PNE03km6neXtwPVQdeFGqh/sbogFcU6A9UcFSYXlJwjcJngeyd77k7M1ooZN9NB8Uctfu0FYFc/TwOmFMMAAQEooIc+f82HMyCRhdaGE0MM9+GcXbL+ZYylGKUnrNUOioDV/ted+Rs2gwFpY2E8y8aTokGFPPu2mDEMxMeeIarcNDdCVegW6Q9s3wRlDhxd+fA4ySN6+uojP1QH0gL+LHIgijo3AQhPdtreEntIWgg8RWBvmVKix0DejTTRxpsagr96BCt8bQHr7MiYEUaTozEMkAqCdWyvaXZT6l3I2VonRqqqvNL+dsxxhtSyM/GlwczaQWOrr241a2rckriBCQprB0K1vtt0I/ghIrPESawbfk9NWZyaYDrDmyIrZp7fkCdFm6qzX79GagxIt7DAjAjm5ULTcUK+MSNoY2z1mZ+JHxWTnMQ0djlaB0wFn5TcEhh3h5WbkMEYY6cbgzRh0QtRPe8vkd5xzAthE8tk1CdMnbJj9ddczwIN4ZFrwyZcSjKHZbbpxugt3+6/8geqbPhNikfC1Ucpxjb1ObZkhflaAvN7bxJd0Z3KY=
