version: "2.1"
orbs:
  go: circleci/go@1.5.0
  codecov: codecov/codecov@1.1.3
jobs:
  test:
    executor:
      name: go/default
      tag: "1.15"
    steps:
      - checkout
      - go/mod-download-cached
      - go/test:
          covermode: atomic
          failfast: true
          race: true
      - codecov/upload:
          file: cover-source.out
  release:
    executor:
      name: go/default
      tag: "1.15"
    steps:
      - checkout
      - run:
          name: Release
          command: bash <(curl -sL https://git.io/goreleaser) release
workflows:
  main:
    jobs:
      - test
      - release:
          context: github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
