name: Go application

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.20"
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run tests
        run: go test -race -coverprofile=coverage.out -covermode=atomic -v ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
      - name: Run lints
        run: pre-commit run --all-files
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.20"
      - name: Run tests
        run: go test -race -v ./...
